### ISSUE TITLE
[BUG] - Network traffic leaks during reconnections

### ISSUE THREAD

**Issue by Avamander** [tprasadtp/protonvpn-docker#122]
### Version of `protonvpn-docker`

5.2.1

### Credential & Plan

- [X] I have verified that my VPN credentials are valid
- [X] I am using OpenVPN credentials and **not** my proton account credentials.
- [X] I have verified that the servers I am trying to connect to are available under my plan.

### System Architecture

x86_64

### Running on a NAS?

No

### Container Runtime

Docker with defaults

### Version of Kubernetes

NA

### Version of docker/podman runtime

20.10.12

### Troubleshooting

- [X] I have tried steps mentioned in [TROUBLESHOOTING](https://tprasadtp.github.io/protonvpn-docker/#/troubleshooting)
- [X] I am using latest version of the docker image

### Relevant log output

```
[WARNING ] Reconnecting... 
[ERROR   ] Failed to reconnect 
[WARNING ] Trying with a fresh connection! 
[INFO    ] resolv.conf.backup - not found 
[NOTICE  ] Using fastest server from COUNTRY: XX 
[ERROR   ] There is no OpenVPN Process!! 
[WARNING ] Reconnecting... 
```

### Code of Conduct & PII Redaction

- [X] I agree to follow this project's Code of Conduct
- [X] I have removed any sensitive personally identifying information(PII) and secrets from in this issue report.

**Comment by draotth** [comment]
It looks like this could be fixed as easily as enabling the killswitch permanently in the docker container:
`protonvpn-cli ks --permanent`

Source: https://protonvpn.com/support/linux-vpn-tool/#cli

**Comment by mike-lloyd03** [comment]
I'm seeing this problem as well. Is there a way to kill network connectivity during reconnections to avoid leaks?

**Comment by mike-lloyd03** [comment]
It seems this is exactly what the [kill switch](https://protonvpn.com/support/what-is-kill-switch/) feature is intended to do. Is there any way to implement this here?

**Comment by mike-lloyd03** [comment]
Looks like this has already been addressed [here](https://github.com/tprasadtp/protonvpn-docker/blob/af8ef02c066748a0817a3c8d98902427a3f3090c/docs/limitations.md).

**Comment by paya-cz** [comment]
So what's the go-to workaround for this? Having traffic leaks for a VPN is really bad.

I guess we just have to use a single server WireGuard container instead?

**Comment by Avamander** [comment]
@paya-cz You can create post-up and pre-down iptables rules for it.
