### ISSUE TITLE
[BUG] -  Community client no longer works with most servers

### ISSUE THREAD

**Issue by maclarel** [tprasadtp/protonvpn-docker#126]
### Version of `protonvpn-docker`

NA

### Credential & Plan

- [X] I have verified that my VPN credentials are valid
- [X] I am using OpenVPN credentials and **not** my proton account credentials.
- [X] I have verified that the servers I am trying to connect to are available under my plan.

### System Architecture

NA

### Running on a NAS?

No

### Container Runtime

Docker with defaults

### Version of Kubernetes

NA

### Version of docker/podman runtime

NA

### Troubleshooting

- [X] I have tried steps mentioned in [TROUBLESHOOTING](https://tprasadtp.github.io/protonvpn-docker/#/troubleshooting)
- [X] I am using latest version of the docker image

### Any additional info

The recent changes with ProtonVPN's plans saw the end of access to many of their servers that were previously accessible with the community maintained client. At this point, regardless of credentials, that client can seemingly now only access three free servers (US/NA/JP).

The "official" move here is to go over to their new "official" (and closed source 😢 ) client, however it doesn't (can't?) run headless, making setup a huge pain in docker.

With that said, they've also now added Wireguard support more formally. Given that Kill Switch was iffy functionality anyway, moving to Wireguard may be the best of both worlds for this setup though it does tie you to one specific server on the ProtonVPN side.

In any case, this unfortunately makes this project in it's current form a bit obsolete, however it has still been incredibly helpful over the past few years, and has certainly inspired [my follow-up](https://github.com/maclarel/homelab/commit/570dc5c70ac4baf06eb72d418cddc9ffd0c514fa) which uses https://github.com/linuxserver/docker-wireguard.

Not sure if you'll want to adopt the Wireguard approach, or figure out a way to use the official ProtonVPN client, but figured I'd give you a heads up as you've been maintaining this for a while <3

### Code of Conduct & PII Redaction

- [X] I agree to follow this project's Code of Conduct
- [X] I have removed any sensitive personally identifying information(PII) and secrets from in this issue report.

**Comment by oatmealm** [comment]
@maclarel thabls for the explanation... I've noticed the container was performing really bad and only selecting "free" server even though I have the basic tier. 

I've adapter my setup to docker-wireguard and it seem to work well. Being tied to one particular server is not a proble, but the profiles generated and download from the account page, are they limited to 24hrs?

10x

**Comment by maclarel** [comment]
> I've adapter my setup to docker-wireguard and it seem to work well. Being tied to one particular server is not a proble, but the profiles generated and download from the account page, are they limited to 24hrs?

I don't think so. I'm still using the same config on my end as when I submitted this Issue and it's working fine.

**Comment by jgwehr** [comment]
Thanks for this! I've just gotten started and, although I haven't had issues with this container, I like the idea of shifting over to linuxserver anyway.

Sort of related question (I haven't found an answer to): have you been able to predefine or get the "random" port Proton provides to then pass to qBittorrent? This may be a Windows-only feature, still. In which case, I guess my question is whether people are just "living with that" or if there's a configuration I've missed. Thanks!

**Comment by jgwehr** [comment]
Ah, okay! Most likely my misunderstanding then. [ProtonVPN reveals a special forwarded port](https://protonvpn.com/support/port-forwarding/) for their P2P servers to have the best performance, at least in the Windows Client. Each re/connection generates a new port.
I assumed something similar existed for other connection types. Still learning - cheers!
