### ISSUE TITLE
[BUG] -  Cannot connect to port in another network

### ISSUE THREAD

**Issue by mazx4960** [tprasadtp/protonvpn-docker#141]
### Version of `protonvpn-docker`

NA

### Credential & Plan

- [X] I have verified that my VPN credentials are valid
- [X] I am using OpenVPN credentials and **not** my proton account credentials.
- [X] I have verified that the servers I am trying to connect to are available under my plan.

### System Architecture

NA

### Running on a NAS?

No

### Container Runtime

Docker with defaults

### Version of Kubernetes

NA

### Version of docker/podman runtime

NA

### Troubleshooting

- [X] I have tried steps mentioned in [TROUBLESHOOTING](https://tprasadtp.github.io/protonvpn-docker/#/troubleshooting)
- [X] I am using latest version of the docker image

### Any additional info

Accessing the port through on the host machine yields no error. However, when trying to connect from another machine results in a connection timeout. The machine used to connect to the port is in a different subnet from the from the host machine.

### Code of Conduct & PII Redaction

- [X] I agree to follow this project's Code of Conduct
- [X] I have removed any sensitive personally identifying information(PII) and secrets from in this issue report.

**Comment by jlxip** [comment]
Can confirm. The issue is not accesing from another machine per se, but the interface the VPN container opens the ports to. `lo` works fine, but any other will not work.

**Comment by jlxip** [comment]
Got a workaround. I've tried to do a version of this inside of the `vpn` container, but no luck. Assuming `vpn` is on the subnet `172.17.0.0/24` and that host is `.1`, run on the host:
```
sudo iptables -t nat -A POSTROUTING ! -s 172.17.0.0/24 -p tcp --dport 9091 -j SNAT --to 172.17.0.1
```

**Comment by Ludofloria** [comment]
Have you use Split Tunneling, as per the documentation?

You just have to use the env var `PROTONVPN_EXCLUDE_CIDRS` with a commat-separated list of your local CIDR, so those networks doesn't get forwarded through the VPN
