### ISSUE TITLE
[BUG] -  Webinterfaces not available when connection container through ProtonVPN

### ISSUE THREAD

**Issue by Smiggel** [tprasadtp/protonvpn-docker#146]
### Version of `protonvpn-docker`

Latest

### Credential & Plan

- [X] I have verified that my VPN credentials are valid
- [X] I am using OpenVPN credentials and **not** my proton account credentials.
- [X] I have verified that the servers I am trying to connect to are available under my plan.

### System Architecture

aarch64

### Running on a NAS?

No

### Container Runtime

None of the above, I have mentioned the details in additional info section.

### Version of Kubernetes

NA

### Version of docker/podman runtime

> Client:
>  Context:    default
>  Debug Mode: false
>  Plugins:
>   app: Docker App (Docker Inc., v0.9.1-beta3)
>   buildx: Docker Buildx (Docker Inc., v0.9.1-docker)
>   compose: Docker Compose (Docker Inc., v2.10.2)
> 
> Server:
>  Containers: 6
>   Running: 6
>   Paused: 0
>   Stopped: 0
>  Images: 9
>  Server Version: 20.10.18
>  Storage Driver: overlay2
>   Backing Filesystem: extfs
>   Supports d_type: true
>   Native Overlay Diff: true
>   userxattr: false
>  Logging Driver: json-file
>  Cgroup Driver: systemd
>  Cgroup Version: 2
>  Plugins:
>   Volume: local
>   Network: bridge host ipvlan macvlan null overlay
>   Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
>  Swarm: inactive
>  Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
>  Default Runtime: runc
>  Init Binary: docker-init
>  containerd version: 9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
>  runc version: v1.1.4-0-g5fd4c4d
>  init version: de40ad0
>  Security Options:
>   seccomp
>    Profile: default
>   cgroupns
>  Kernel Version: 5.15.61-v8+
>  Operating System: Debian GNU/Linux 11 (bullseye)
>  OSType: linux
>  Architecture: aarch64
>  CPUs: 4
>  Total Memory: 7.678GiB
>  Name: PiBox
>  ID: W4EF:D37U:KGZA:WDDR:PJZ7:VTPM:AJS3:VOCX:RKVE:TDGX:DCT4:6HJO
>  Docker Root Dir: /var/lib/docker
>  Debug Mode: false
>  Registry: https://index.docker.io/v1/
>  Labels:
>  Experimental: false
>  Insecure Registries:
>   127.0.0.0/8
>  Live Restore Enabled: false

### Troubleshooting

- [X] I have tried steps mentioned in [TROUBLESHOOTING](https://tprasadtp.github.io/protonvpn-docker/#/troubleshooting)
- [X] I am using latest version of the docker image

### Any additional info

When connecting other Docker containers through ProtonVPN, the web interfaces are not available. I have set the ports and expose ports but the interface is nog available. 

For example. When running Transmission (https://hub.docker.com/r/linuxserver/transmission) through ProtonVPN, I see that Transmission has the IP adres of the ProtonVPN container. However, when I try to access the web interface on port: 9091, I can not access it.

### Code of Conduct & PII Redaction

- [X] I agree to follow this project's Code of Conduct
- [X] I have removed any sensitive personally identifying information(PII) and secrets from in this issue report.

**Comment by RetroKim** [comment]
Has anyone found a solution to this?

**Comment by Smiggel** [comment]
Not yet. Switched to an other VPN provider for now.

**Comment by mike-lloyd03** [comment]
I'm having the same problem with getting Radarr to work. Connecting to the Radarr web interface just hangs.

**Comment by mike-lloyd03** [comment]
Guys, the answer is pinned on the issues page (#15).

Setting `PROTONVPN_EXCLUDE_CIDRS` to the CIDR of my local network fixed it.

```bash
PROTONVPN_EXCLUDE_CIDRS="192.168.0.0/24"
```

**Comment by Smiggel** [comment]
`version: '3.4'
services:
  protonvpn:
    container_name: protonvpn
    environment:
      PROTONVPN_COUNTRY: NL
      PROTONVPN_USERNAME:xxx
      PROTONVPN_PASSWORD: xxx
      PROTONVPN_TIER: 0
      PROTONVPN_SERVER: NL
      PROTONVPN_EXCLUDE_CIDRS: 192.168.1.0/24
    image: ghcr.io/tprasadtp/protonvpn:latest
    restart: unless-stopped
    networks:
      - internet
      - proxy
    network_mode: bridge
    cap_add:
      - NET_ADMIN #required
    devices:
      - /dev/net/tun:/dev/net/tun
    expose:
      - 8000:8000
      - 9093:9091
  pyload:
    depends_on:
      - protonvpn
    container_name: pyload
    environment:
      TZ: "Europe/Amsterdam"
      PGID: "1000"
      PUID: "100"
    image: linuxserver/pyload:latest
    restart: unless-stopped
    network_mode: service:protonvpn
    volumes:
      - /srv/dev-disk-by-uuid-xxxx/Configs/ProtonVPN:/config
      - /srv/dev-disk-by-uuid-xxxx/Configs/Downloads/:/downloads/:rw
volumes:
  config:
networks:
  internet:
  proxy:
    internal: true`
    
I am testing with the above configuration and still no luck. I can see that containers connected to the VPN container have the same IP as the Protonvpn container. However, the interface is not loading. Anyone else have any tips?

I have the same kind of setup using a NordVPN container and that works. However, my subscription is ending and want to move to ProtonVPN. But it should work first. :)
