### ISSUE TITLE
How to check if vpn is running?

### ISSUE THREAD

**Issue by Chetan11-dev** [tprasadtp/protonvpn-docker#152]
### Version of `protonvpn-docker`

NA

### Credential & Plan

- [X] I have verified that my VPN credentials are valid
- [X] I am using OpenVPN credentials and **not** my proton account credentials.
- [X] I have verified that the servers I am trying to connect to are available under my plan.

### System Architecture

NA

### Running on a NAS?

No

### Container Runtime

Docker with defaults

### Version of Kubernetes

NA

### Version of docker/podman runtime

NA

### Troubleshooting

- [ ] I have tried steps mentioned in [TROUBLESHOOTING](https://tprasadtp.github.io/protonvpn-docker/#/troubleshooting)
- [ ] I am using latest version of the docker image

### Any additional info

How can I check if vpn is running from other container?

### Code of Conduct & PII Redaction

- [X] I agree to follow this project's Code of Conduct
- [X] I have removed any sensitive personally identifying information(PII) and secrets from in this issue report.

**Comment by beardstack** [comment]
`/usr/bin/healthcheck`
