### ISSUE TITLE
Not set CFG_TIER for Visionary Plan

### ISSUE THREAD

**Issue by batbast** [tprasadtp/protonvpn-docker#16]
Into file  protonvpn-docker/root/etc/cont-init.d/70-vpn-setup, line 28

Actual content:   3 | visionary | Visionary | VISIONARY) echo "Yo Dwag! You have Visionary Plan!";PROTONVPN_TIER=3;;
---
Correction:   3 | visionary | Visionary | VISIONARY) echo "Yo Dwag! You have Visionary Plan!";CFG_TIER=3;;

**Comment by tprasadtp** [comment]
Fixed in 3.0.0
