### ISSUE TITLE
[BUG] -  failed to resolve DNS domain

### ISSUE THREAD

**Issue by clemone210** [tprasadtp/protonvpn-docker#211]
### Version

latest

### Credential Validation

- [X] I have verified that the servers I am trying to connect to are available under my plan.
- [X] I have verified that my generated Wireguard private keys are valid and have required features (Netshield Ad-blocker, VPN accelerator etc) are enabled.
- [X] I am using a valid server name (either fully qualified DNS name like `nl-free-127.protonvpn.net` or server name like `NL#1`) as mentioned in the docs.

### System Architecture

x86_64

### Kernel Version

5.15.0-69-generic

### Running on a NAS?

No

### Runtime

docker

### Version of Runtime

Client:
 Context:    default
 Debug Mode: false
 Plugins:
  compose: Docker Compose (Docker Inc.)
    Version:  v2.17.2
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 31
  Running: 30
  Paused: 0
  Stopped: 1
 Images: 87
 Server Version: 23.0.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc version: v1.1.5-0-gf19387a
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-69-generic
 Operating System: Ubuntu 22.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 251.4GiB
 Name: Ubuntu-2204-jammy-amd64-base
 ID: 1d906273-e653-4e83-b989-82649379f5e5
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

### Your configuration

```markdown
protonvpn:
    image: ghcr.io/tprasadtp/protonwire:${PROTONVPN_VERSION}
    container_name: protonvpn
    #network_mode: bridge
    init: true
    restart: unless-stopped
    env_file:
      - ${CONFIG_FOLDER}/protonvpn/.env
      - .env
    cap_add:
      - NET_ADMIN
    sysctls:
      net.ipv4.conf.all.rp_filter: 2
      net.ipv6.conf.all.disable_ipv6: 1
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - type: tmpfs
        target: /tmp
      - type: bind
        source: /etc/protonwire/private-key/private.key
        target: /etc/protonwire/private-key
        read_only: true
    ports:
      - 5076:5076
```

### Troubleshooting & Runtime

- [X] I have read [FAQ](https://github.com/tprasadtp/protonvpn-docker/blob/master/docs/faq.md) and [Troubleshooting](https://github.com/tprasadtp/protonvpn-docker/blob/master/docs/help.md).
- [X] I am **NOT** using container runtime which use user-mode networking, [Docker Rootless](https://docs.docker.com/engine/security/rootless/), [gVisor](https://gvisor.dev), [Podman Rootless](https://github.com/containers/podman/blob/main/rootless.md) etc.
- [X] I am using latest stable version

### Container/Pod/systemd log output

```log
none
```

### Any additional info

protonvpn        | [NOTICE  ] Skipped validating default IPCHECK_URL 
protonvpn        | [INFO    ] Refresing server metadata (for node-de-16.protonvpn.net) 
protonvpn        | [SUCCESS ] Successfully refreshed server metadata 
protonvpn        | [SUCCESS ] Server node-de-16.protonvpn.net is online 
protonvpn        | [SUCCESS ] WIREGUARD_PRIVATE_KEY(YG6ek**********) is a valid key 
protonvpn        | [SUCCESS ] net.ipv4.conf.all.rp_filter is already set to 2 
protonvpn        | [NOTICE  ] Creating WireGuard Interface - protonwire0 
protonvpn        | [INFO    ] Setting WireGuard interface address - 10.2.0.2 
protonvpn        | [INFO    ] Setting WireGuard interface MTU to 1480 
protonvpn        | [SUCCESS ] Setting WireGuard private key 
protonvpn        | [INFO    ] Bringing WireGuard interface up 
protonvpn        | [SUCCESS ] Setting fwmark on WireGuard interface to - 0xca6d 
protonvpn        | [INFO    ] Configuring wireguard table 51821 (IPv4) 
protonvpn        | [INFO    ] Configuring IP rules (IPv4) 
protonvpn        | [SUCCESS ] Successfully configured DNS (resolvconf) 
protonvpn        | [INFO    ] Verifying connection 
^Xprotonvpn        | [ERROR   ] Failed to resolve DNS domain (https://protonwire-api.vercel.app/v1/client/ip) 
protonvpn        | [ERROR   ] Retry (1/3) after 2 seconds 
protonvpn        | [ERROR   ] Failed to resolve DNS domain (https://protonwire-api.vercel.app/v1/client/ip) 
protonvpn        | [ERROR   ] Retry (2/3) after 2 seconds 
protonvpn        | [ERROR   ] Failed to resolve DNS domain (https://protonwire-api.vercel.app/v1/client/ip) 
protonvpn        | [ERROR   ] Retry (3/3) after 2 seconds 
protonvpn        | [ERROR   ] Failed to verify connection! 
protonvpn        | [SUCCESS ] Successfully restored DNS(resolvconf) 
protonvpn        | [INFO    ] IPv6 disabled, skipping IPv6 routes and rules 
protonvpn        | [INFO    ] Removing IP routing rules 
protonvpn        | [INFO    ] Removing WireGuard interface 
protonvpn exited with code 1

### Code of Conduct & PII Redaction

- [X] I agree to follow this project's Code of Conduct.
- [X] I have removed any sensitive personally identifying information(PII) and secrets from in this issue report.

**Comment by rhtrplx** [comment]
Hello, I'm facing this issue, did you find a workaround ?

**Comment by exander77** [comment]
Same issue.

**Comment by eebette** [comment]
https://github.com/tprasadtp/protonvpn-docker/issues/236#issuecomment-1657006429
