### ISSUE TITLE
Failing checkups

### ISSUE THREAD

**Issue by sebastianarena** [tprasadtp/protonvpn-docker#27]
Hi!
Loved the docker container!
It seems I have kind of a problem with the health checkups it does internally.
This is what the logging shows:

```
[Service - INIT] PROTONVPN_SVC_DISCONNECTING: 0
[Service - CHCK] #2 Failed!
[Service - CHCK] connected to # instead of #AR
```

Every check, up until the third, and then reconnects.
The weird part is the connection is working perfectly.
I use the connection from different containers, and they work, and see the proper IP from Proton.

So, how is the container doing the checkups? Why does it seem to be failing?
Any help is appreciated!

**Comment by tprasadtp** [comment]
Can you please exec into the container and run `curl -vv https://ipinfo.io` and check if it executes?( Please redact any personal information like IP address in the output). Healthcheck verifies whether country you connected matches with public IP address you got from the VPN.

**Comment by sebastianarena** [comment]
@tprasadtp thank you for this! It turns out, that domain was being blocked by my internal Pi-Hole! Whitelisting it solved the issue. Maybe something to add to the README so people know the container uses this service and can do the same I did in case they use their own DNS.

**Comment by tprasadtp** [comment]
It is already in the README.

**Comment by sebastianarena** [comment]
I don’t know how I missed it. Sorry for wasting your time. Great container! Already starred it! Thanks
