### ISSUE TITLE
[QUESTION]: No way of finding DNS name of server anymore?

### ISSUE THREAD

**Issue by stasj145** [tprasadtp/protonvpn-docker#292]
### Version

7.2.9

### Support Request

The documentation states that we should use a "DNS name like 'node-nl-03.protonvpn.net'". This is precisely what I have been doing for the last 2 years and has worked flawlessly. (Using names like "NL#1" has never worked for me, even though I tried multiple times). The problem with that is, that the old way of getting the DNS name of a server no longer works. The web-ui has been updated and does not have the little arrow anymore (see screenshot). I have also not found any other way of finding the DNS name.
![firefox_nQOTfCXBcl](https://github.com/tprasadtp/protonvpn-docker/assets/50620058/d5461c0d-2d61-4876-81f7-cb61a3aaaf5f)

With names like "NL#1" never working for me and not beeing able to find the DNS name anymore, there is currently no way for me to connect to a server.

Is there anything i am missing here?

### Code of Conduct & PII Redaction

- [x] I have verified that this feature request is not a duplicate and is not not addressed by the [FAQ](https://github.com/tprasadtp/protonvpn-docker/blob/master/docs/faq.md) and [Troubleshooting](https://github.com/tprasadtp/protonvpn-docker/blob/master/docs/help.md).
- [X] This is not a bug report or feature request.
- [X] I agree to follow this project's Code of Conduct.
- [X] I have removed any sensitive personally identifying information(PII) and secrets from in this issue report.

**Comment by tprasadtp** [comment]
Well, its _not documented_, but try using server IP.

**Comment by stasj145** [comment]
Well... using the IP kinda worked.
I got the following output. There was no connection made and the container restarted.

```
[•] Verifying IPCHECK_URL - https://icanhazip.com 

[•] Refresing server metadata (for 185.107.56.143) 

[•] Successfully refreshed server metadata 

[•] Server 185.107.56.143 is online 

[•] WIREGUARD_PRIVATE_KEY(**********) is a valid key 

[•] net.ipv4.conf.all.rp_filter is already set to 2 

[•] Creating WireGuard Interface - protonwire0 

[•] Setting WireGuard interface address - 10.2.0.2 

[•] Setting WireGuard interface MTU to 1480 

[•] Configured WireGuard private key 

[•] WireGuard interface is configured with peer - xxxxxxxxxx=(185.107.56.143) 

[•] Bringing WireGuard interface up 

[•] Configured fwmark on WireGuard interface to - 0xca6d 

[•] Creating routes (IPv4) 

[•] DNS is is set to 10.2.0.1 via /etc/resolv.conf 

[•] Successfully configured DNS (resolvconf) 

[•] Verifying connection 

[•] Expected to be connected to server 185.107.56.143, but is connected to NL-FREE#406151(node-nl-191.protonvpn.net) 

[•] Retry (1/5) after 2 seconds 

[•] Expected to be connected to server 185.107.56.143, but is connected to NL-FREE#406151(node-nl-191.protonvpn.net) 

[•] Retry (2/5) after 2 seconds 

[•] Expected to be connected to server 185.107.56.143, but is connected to NL-FREE#406151(node-nl-191.protonvpn.net) 

[•] Retry (3/5) after 2 seconds 

[•] Expected to be connected to server 185.107.56.143, but is connected to NL-FREE#406151(node-nl-191.protonvpn.net) 

[•] Retry (4/5) after 2 seconds 

[•] Expected to be connected to server 185.107.56.143, but is connected to NL-FREE#406151(node-nl-191.protonvpn.net) 

[•] Retry (5/5) after 2 seconds 

[•] Failed to verify connection! 

[•] Reverted DNS configuration 

[•] Successfully restored DNS(resolvconf) 

[•] Removing IP rule (IPv4) 

[•] Removing WireGuard interface 

[•] Verifying IPCHECK_URL - https://icanhazip.com 

[•] Existing metadata(NL-FREE#406151/node-nl-191.protonvpn.net) does not belong to 185.107.56.143 

```
So this didn't work. Since the output seemed to show a DNS name for the server, I tried that and it worked. I was able to connect.
Although, this is not exactly a great workaround for the future. Maybe this could be automated? IDK.

Thanks!
