### ISSUE TITLE
Must be restarted after a few days of use 

### ISSUE THREAD

**Issue by hadim** [tprasadtp/protonvpn-docker#7]
I use it with a qbitorrent container and the container cant download at all after he few days. I must restart both containers to make it wok.

**Comment by hadim** [comment]
@tprasadtp any idea?

**Comment by tprasadtp** [comment]
Hard to tell without looking at logs or more details.  Other containers share network stack of protonvpn container so if protonvpn container is restarted others need to restarted as well.
Try to run container with env variable
```
DEBUG=1
```

**Comment by hadim** [comment]
Trying to run with `DEBUG=1` right now. I will report here next time the connection is broken.

**Comment by hadim** [comment]
I am using p2p and wasn't specifying a p2p friendly server. That could be related to this. I will close here and reopen if it happens again.
