### ISSUE TITLE
[BUG] - support for Wireguard

### ISSUE THREAD

**Issue by water1309** [tprasadtp/protonvpn-docker#72]
### Version of `protonvpn-docker`

ghcr.io/tprasadtp/protonvpn:4.2.1

### Credential & Plan

- [X] I have verified that my VPN credentials are valid
- [X] I am using OpenVPN credentials and **not** my proton account credentials.
- [X] I have verified that the servers I am trying to connect to are available under my plan.

### System Architecture

X86_64

### Running on a NAS?

Yes

### Container Runtime

Docker with defaults

### Version of Kubernetes

NA

### Version of docker/podman runtime

NA

### 

- [ ] I have tried debugging with compose file provided as mentioned in [TROUBLESHOOTING](https://tprasadtp.github.io/protonvpn-docker/docs/troubleshooting/)

### Any additional info

Thank you for this awesome container!

This is of course not an actual bug, but there are no other templates. Also, am I missing something or is there no field for the actual bug?

Not related, but I can't seem to figure out how to use docker compose secrets withe the protonvpn username and password.

### Code of Conduct & PII Redaction

- [X] I agree to follow this project's Code of Conduct
- [X] I have removed any sensitive personally identifying information(PII) and secrets from in this issue report.

**Comment by oatmealm** [comment]
I've noticed how quickly the proton app connects on iOS, and subjectively, how it feels much more performant. Would be great to see this supported.

**Comment by nullpanda** [comment]
I would like to +1 this request as well, the performance boost would be immense.
