### ISSUE TITLE
[FEATURE] -  Better Documentation for Secure Core

### ISSUE THREAD

**Issue by Motzkiste** [tprasadtp/protonvpn-docker#80]
### Version of `protonvpn-docker`

5.0.1

### Details about Feature/Enhancement

Hi,

I don't understand how to set the parameters to use ProtonVPNs Secure Core. 
I'm using ProtonVPN with a Pro/Plus-Plan and Secure Core works fine on PC/Phone.

It would be really nice if you could tell us what we have to set to use Secure Core.
And I would suggest to add this to your documentation.

Thank you 😄 

### Code of Conduct & PII Redaction

- [X] I agree to follow this project's Code of Conduct
- [X] I have removed any sensitive personally identifying information(PII) and secrets from in this issue report.

**Comment by tprasadtp** [comment]
As defined in [docs](https://tprasadtp.github.io/protonvpn-docker/#/README?id=protonvpn_server), You must set `PROTONVPN_TIER` to `2` and set `PROTONVPN_SERVER` to one of the secure core servers like `IS-DE#1`. Secure core is nothing special in terms of openvpn client, its just a normal openvpn server.
